### PR TITLE
Add new icon plugin-throw and plugin-titleinfo

### PR DESCRIPTION
**Pull request by Eignar17**

### CODE REVIEW

**Comment by soreau** [comment]
@Eignar17 Hi, these icons look nice, did you create them? The titleinfo icon kinda strikes me as an icon for when there is no icon because of the question mark. Is there a way to change the '?' to a lowercase 'i' for title info?

Also I would like to see icons pushed to their relevant source repos instead of ccsm, where they are installed to a common location where newer versions of ccsm look. Actually the only icon that currently installs this way is vidcap icon, which could be used as an example.

If you can change the '?' to an 'i' for titleinfo, I can come up with a patch for -experimental to add/install the icons, with you as author.

**Comment by Eignar17** [comment]
@soreau plugin-throw.svg is to compiz-fusion-icons and plugin-titleinfo.svg create me ok '?' to 'i' is new plugins in to respective icon and classic not. is view icon for your new vercion plugin showrepaint https://github.com/ethus3h/compiz-plugins-community/blob/master/icons/plugin-showrepaint.svg

**Comment by Eignar17** [comment]
@soreau your icon vidcap not install, my fix problem

**Comment by soreau** [comment]
The new titlebar info icon looks great. I'll make a patch for plugins-main (titleinfo) and plugins-experimental (throw) when I have time. Thanks for your work.

**Comment by Eignar17** [comment]
@soreau  lol my add my icons in to compiz your programing in to plugins :+1:

**Pull request closed without merging**
